apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coverage-api
spec:
  rules:
    - host: coverage-api.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: coverage-api
                port:
                  number: 80
